name: Build and Publish Azure Artifact

on:
  workflow_dispatch:
  
env:
  AZURE_ARTIFACTS_FEED_URL: https://pkgs.dev.azure.com/July2021/TerraformSample/_packaging/rahulartifactfeed/maven/v1    
  BUILD_CONFIGURATION: 'Release'    # set this to the appropriate build configuration
  JAVA_VERSION: '11' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1- Checkout
        uses: actions/checkout@v2

      - name: Step 2- Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
          source-url: ${{ env.AZURE_ARTIFACTS_FEED_URL }}
          server-id: "rahulartifactfeed"
          server-username: "July2021"
          server-password: ${{ secrets.AZURE_ARTIFACTS_PAT }} 
