name: Build and Publish Azure Artifact

on:
  workflow_dispatch:
  
env:
  AZURE_ARTIFACTS_FEED_URL: https://pkgs.dev.azure.com/July2021/TerraformSample/_packaging/rahulartifactfeed/maven/v1    
  BUILD_CONFIGURATION: 'Release'    # set this to the appropriate build configuration
  JAVA_VERSION: '11' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1- Checkout
        uses: actions/checkout@v2
          
      - name: Step 2 - Maven package creation
        run: mvn -B archetype:generate -DgroupId="com.domain" -DartifactId="demo"
