# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy war app to Azure Web App - rahultestwebapp04

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2     

      - name: step-1 ACR login
        uses: azure/docker-login@v1
        with:
          login-server: rahultestwebapp04acr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Step 2 List the current directory
        run: ls -a
        
      - name: Step-3 List the target directory
        run: |
          cd target
          ls -a 
          
      - name: Step -4 docker build and push
        run: |
          docker build . -t demo:1.0
          docker push demo:1.0
